apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: flaskserver
  name: flaskserver
  namespace: sklearnmodelservice
spec:
  replicas: 1
  selector:
    app: flaskserver
    deploymentconfig: flaskserver
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      labels:
        app: flaskserver
        deploymentconfig: flaskserver
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS
              valueFrom:
                secretKeyRef:
                  name: miniosecrets
                  key:  minioaccess
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: miniosecrets
                  key:  miniosecret
          image: >-
            docker-registry.default.svc:5000/sklearnmodelservice/flaskserver
          imagePullPolicy: Always
          name: flaskserver
          ports:
            - containerPort: 5000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources: {}
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - flaskserver
        from:
          kind: ImageStreamTag
          name: 'flaskserver:latest'
          namespace: sklearnmodelservice
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/sklearnmodelservice/flaskserver
      type: ImageChange