apiVersion: v1
kind: Route
metadata:
  labels:
    app: flaskserver
  name: flaskserver
  namespace: sklearnmodelservice
spec:
  port:
    targetPort: 5000-tcp
  to:
    kind: Service
    name: flaskserver

