
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskserver
  name: flaskserver
  namespace: sklearnmodelservice
spec:
  clusterIP: 172.30.212.214
  ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: flaskserver
  type: ClusterIP